### ISSUE TITLE
a question about the created .obj file

### ISSUE THREAD

**Issue by ljcccccccccccccccccc** [thu-ml/AT3D#1]
Hi,

I implemented your code on github about AT3D, but the built .obj file can't be printed in 3D printer because its thickness and height is only 1mm, I don't know what's wrong.

Would you please do me a favor to explain if there is any way to solve this problem

Best regards,
Keli.

**Comment by elenacliu** [comment]
Yes, the generated .obj file has no thickness (because it just has one layer of mesh), to print it with a 3D printer you should thicken it through code or 3D mesh edit software.

**Comment by elenacliu** [comment]
since there are no updates to this problem I will close it, but you can reopen it if you'd like
