### ISSUE TITLE
Victim identity with expression and head pose of attacker

### ISSUE THREAD

**Issue by SaharHusseini** [thu-ml/AT3D#4]
Hello, 
Could you kindly provide guidance on reconstructing a 3D mask that captures the victim's identity but facial expression and the head pose of the attacker?

I have tried the following trials
For the mask argument, I tried to use “whole” by which I wanted to put the whole victim face on the attacker face, however I get the following error
Traceback (most recent call last):
  File "./benchmark/3dmm_attack.py", line 245, in <module>
    main()
  File "./benchmark/3dmm_attack.py", line 74, in main
    ) in tqdm(loader, total=len(loader) / args.batch_size):
ValueError: too many values to unpack (expected 10)

Another test that I’v done is that I remove “exp” from the  – need attack argument list, however still the expression of the 3D mask is the same as victim specially in the mouth area. 

Thank you in advance
Sahar

**Comment by elenacliu** [comment]
I'm sorry that last month I had another paper ddl to rush against. Have you solved the problem yet?

**Comment by SaharHusseini** [comment]
Hello, 

Yes I already have solved the problem. Thank you for your response.

BR,
Sahar
